"""Testing alembic 2

Revision ID: 7891be10df13
Revises: aa574a6fc747
Create Date: 2021-05-12 20:53:30.299392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7891be10df13'
down_revision = 'aa574a6fc747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_records_create_ts', table_name='test_records')
    op.drop_index('ix_test_records_id', table_name='test_records')
    op.drop_table('test_records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('create_ts', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_records_id', 'test_records', ['id'], unique=False)
    op.create_index('ix_test_records_create_ts', 'test_records', ['create_ts'], unique=False)
    # ### end Alembic commands ###
