"""Testing alembic

Revision ID: aa574a6fc747
Revises: eba59763108c
Create Date: 2021-05-12 07:51:00.529558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa574a6fc747'
down_revision = 'eba59763108c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_records_create_ts'), 'test_records', ['create_ts'], unique=False)
    op.create_index(op.f('ix_test_records_id'), 'test_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_records_id'), table_name='test_records')
    op.drop_index(op.f('ix_test_records_create_ts'), table_name='test_records')
    op.drop_table('test_records')
    # ### end Alembic commands ###
