"""Testing alembic 3

Revision ID: edd21357f5ad
Revises: 7891be10df13
Create Date: 2021-05-12 20:54:23.532079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd21357f5ad'
down_revision = '7891be10df13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
